name: Java CI with Maven

on: 
  push:
    branches:
    - jamil
    - master
  pull_request:
    branches:
    - '*'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: |
        mvn clean 
        mvn --batch-mode --update-snapshots verify